"""Released-verifiers v1 taskset for the railroad-1959-v0 proof build.

The taskset is deliberately self-contained. Its packaged JSONL is generated by
``scripts/build_prime_railroad_v1.py`` from the pinned Source2Agent build. The
reward implementation mirrors ``volume2gym.DeterministicVerifier`` version 1;
parity is checked across the full taskset by the repository tests.
"""

from __future__ import annotations

import gzip
import hashlib
import json
import re
import unicodedata
from difflib import SequenceMatcher
from importlib.resources import files
from typing import Any, Literal

import verifiers.v1 as vf
from pydantic import BaseModel, ConfigDict, ValidationError

VERIFIERS_VERSION = "0.3.0"
VERIFIERS_RELEASE_COMMIT = "0a4d872f021022310a08ec213a25f4efb4a0244a"
VERIFIER_ID = "volume2gym.deterministic-composite"
VERIFIER_VERSION = "1"
SYSTEM_PROMPT = (
    "Use only the supplied historical source excerpt. Return the requested structured "
    "JSON object. This 1959 text is an evaluation source, not current railroad operating "
    "instruction."
)

SAFETY_COMPONENT = "safety_critical_required_actions"
FORBIDDEN_COMPONENT = "forbidden_unsafe_actions_absent"
RULE_COMPONENT = "correct_applicable_rule_cited"
PROCEDURE_COMPONENT = "procedure_order_correct"
TERMINOLOGY_COMPONENT = "domain_terminology_correct"
WEIGHTS = {
    SAFETY_COMPONENT: 0.40,
    FORBIDDEN_COMPONENT: 0.20,
    RULE_COMPONENT: 0.15,
    PROCEDURE_COMPONENT: 0.15,
    TERMINOLOGY_COMPONENT: 0.10,
}
COMPONENT_ORDER = tuple(WEIGHTS)
_SPACE_RE = re.compile(r"\s+")
_NON_WORD_RE = re.compile(r"[^\w]+", flags=re.UNICODE)


class StructuredAnswer(BaseModel):
    model_config = ConfigDict(extra="forbid")

    applicable_rules: tuple[str, ...] = ()
    situation_type: str | None = None
    required_actions: tuple[str, ...] = ()
    forbidden_actions: tuple[str, ...] = ()
    procedure_order: tuple[str, ...] = ()
    final_answer: str = ""


class Railroad1959Data(vf.TaskData):
    task_id: str
    split: Literal["train", "dev", "test"]
    task_family: str
    knowledge_unit_ids: tuple[str, ...]
    answer_contract: dict[str, Any]
    answer_key: dict[str, Any]
    citations: tuple[dict[str, Any], ...]
    group_id: str
    source_build_id: str
    source_task_sha256: str


class Railroad1959Task(vf.Task[Railroad1959Data]):
    @vf.stop
    async def single_turn(self, trace: vf.Trace) -> bool:
        return trace.num_turns >= 1

    @vf.reward(weight=1.0)
    async def source2agent_reward(self, trace: vf.Trace) -> float:
        ledger = _ledger_for_trace(self.data, trace)
        return float(ledger["total_score"])

    @vf.metric
    async def reward_contract(self, trace: vf.Trace) -> dict[str, float]:
        ledger = _ledger_for_trace(self.data, trace)
        component_scores = {
            f"component.{component['component_id']}": float(component["score"])
            for component in ledger["components"]
        }
        answer = _parse_answer(_response_for_trace(trace))
        reference = str(self.data.answer_key.get("reference_answer") or "")
        fidelity = 0.0
        if answer is not None and reference:
            fidelity = SequenceMatcher(
                None,
                normalize_text(answer.final_answer),
                normalize_text(reference),
            ).ratio()
        return {
            **component_scores,
            "reward.ungated_total": float(ledger["ungated_total_score"]),
            "reward.gate_multiplier": float(ledger["gate_multiplier"]),
            "reward.schema_validity": float(
                ledger["diagnostics"]["schema_validity"]
            ),
            "reward.reference_answer_fidelity_unscored": fidelity,
        }

    async def validate(self, runtime: vf.Runtime) -> bool:
        trace = reference_trace(self)
        await self.score(trace, runtime)
        ledger = trace.info.get("source2agent_reward_ledger")
        return bool(
            trace.reward == 1.0
            and isinstance(ledger, dict)
            and ledger.get("total_score") == 1.0
            and ledger.get("verifier_id") == VERIFIER_ID
        )


class Railroad1959Config(vf.TasksetConfig):
    split: Literal["train", "dev", "test", "all"] = "test"


class Railroad1959Taskset(vf.Taskset[Railroad1959Task, Railroad1959Config]):
    def load(self) -> list[Railroad1959Task]:
        manifest, records = _load_packaged_taskset()
        selected = (
            records
            if self.config.split == "all"
            else [record for record in records if record["split"] == self.config.split]
        )
        return [
            Railroad1959Task(
                Railroad1959Data(
                    idx=int(record["idx"]),
                    name=str(record["task_id"]),
                    description=(
                        "Source2Agent railroad proof task; historical evaluation only."
                    ),
                    prompt=str(record["prompt"]),
                    system_prompt=SYSTEM_PROMPT,
                    timeout=vf.TaskTimeout(agent=120.0, scoring=30.0),
                    task_id=str(record["task_id"]),
                    split=record["split"],
                    task_family=str(record["task_family"]),
                    knowledge_unit_ids=tuple(record["knowledge_unit_ids"]),
                    answer_contract=dict(record["answer_contract"]),
                    answer_key=dict(record["answer_key"]),
                    citations=tuple(record["citations"]),
                    group_id=str(record["group_id"]),
                    source_build_id=str(manifest["source2agent_build_id"]),
                    source_task_sha256=str(manifest["source_task_artifact_sha256"]),
                ),
                self.config.task,
            )
            for record in selected
        ]


def _data_dir():
    return files("railroad_1959_v1").joinpath("data")


def _load_packaged_taskset() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    data_dir = _data_dir()
    manifest_bytes = data_dir.joinpath("taskset-manifest.json").read_bytes()
    manifest = json.loads(manifest_bytes)
    compressed = data_dir.joinpath("taskset.jsonl.gz").read_bytes()
    if _sha256(compressed) != manifest["taskset_gzip_sha256"]:
        raise ValueError("railroad-1959-v1 compressed taskset hash mismatch")
    raw = gzip.decompress(compressed)
    if _sha256(raw) != manifest["taskset_jsonl_sha256"]:
        raise ValueError("railroad-1959-v1 taskset content hash mismatch")
    records = [json.loads(line) for line in raw.splitlines() if line]
    if len(records) != manifest["task_count"]:
        raise ValueError("railroad-1959-v1 task count does not match its manifest")
    return manifest, records


def reference_response(task: Railroad1959Task) -> str:
    key = task.data.answer_key
    return _canonical_json(
        {
            "applicable_rules": list(key.get("applicable_unit_ids") or []),
            "situation_type": task.data.task_family,
            "required_actions": list(key.get("required_actions") or []),
            "forbidden_actions": list(key.get("forbidden_actions") or []),
            "procedure_order": list(key.get("procedure_order") or []),
            "final_answer": str(key.get("reference_answer") or ""),
        }
    )


def reference_trace(task: Railroad1959Task) -> vf.Trace:
    response = reference_response(task)
    deterministic_id = hashlib.sha256(
        f"{task.data.task_id}:symbolic-answer-key".encode()
    ).hexdigest()[:32]
    nodes = [
        vf.MessageNode(
            parent=None,
            message=vf.SystemMessage(role="system", content=SYSTEM_PROMPT),
            sampled=False,
            timestamp=0.0,
        ),
        vf.MessageNode(
            parent=0,
            message=vf.UserMessage(role="user", content=str(task.data.prompt)),
            sampled=False,
            timestamp=0.0,
        ),
        vf.MessageNode(
            parent=1,
            message=vf.AssistantMessage(role="assistant", content=response),
            sampled=False,
            timestamp=0.0,
        ),
    ]
    return vf.Trace(
        id=deterministic_id,
        verifiers=vf.VersionInfo(
            version=VERIFIERS_VERSION,
            commit=VERIFIERS_RELEASE_COMMIT,
        ),
        run=vf.EvalRunInfo(id="railroad-1959-v1-symbolic-reference"),
        task=vf.TraceTask(type=type(task).__name__, data=task.data),
        agent=vf.AgentInfo(
            config=vf.AgentConfig(
                harness=vf.HarnessConfig(id="null"),
                runtime=vf.SubprocessConfig(),
                model="symbolic-answer-key",
                max_turns=1,
            ),
            name="agent",
            trainable=False,
        ),
        nodes=nodes,
        is_completed=True,
        ok=True,
        stop_condition="symbolic-reference",
        timing=vf.Timing(start=0.0),
        info={
            "mode": "symbolic-reference",
            "neural_model": False,
            "hosted_credits_spent": False,
            "symbolic_response": response,
        },
    )


def score_response(
    data: Railroad1959Data,
    response: str | dict[str, Any],
    *,
    response_id: str,
) -> dict[str, Any]:
    answer = _parse_answer(response)
    if answer is None:
        components = [
            _component(
                component_id,
                0.0,
                (),
                "response did not satisfy the structured answer contract",
            )
            for component_id in COMPONENT_ORDER
        ]
        return _ledger(
            data,
            response_id,
            components,
            gate_multiplier=0.0,
            diagnostics={
                "schema_validity": 0.0,
                "source_grounding": 0.0,
                "unsafe_recommendation_detected": 0.0,
                "safety_gate_applied": 1.0,
                "safety_gate_reasons": ["structured answer is invalid"],
            },
        )

    expected = data.answer_key
    required_score, matched_required, missing_required = _coverage(
        expected.get("required_actions") or [], answer.required_actions
    )
    declared_forbidden, matched_forbidden, missing_forbidden = _coverage(
        expected.get("forbidden_actions") or [], answer.forbidden_actions
    )
    unsafe = _intersection(
        expected.get("forbidden_actions") or [],
        (*answer.required_actions, *answer.procedure_order),
    )
    forbidden_score = 0.0 if unsafe else declared_forbidden
    rule_score, matched_rules, missing_rules = _coverage(
        expected.get("applicable_unit_ids") or [], answer.applicable_rules
    )
    procedure_score, matched_procedure = _ordered_coverage(
        expected.get("procedure_order") or [], answer.procedure_order
    )
    missing_procedure = _missing(
        expected.get("procedure_order") or [], matched_procedure
    )
    term_score, matched_terms, missing_terms = _term_coverage(
        expected.get("terms") or [], answer.final_answer
    )
    scores = {
        SAFETY_COMPONENT: required_score,
        FORBIDDEN_COMPONENT: forbidden_score,
        RULE_COMPONENT: rule_score,
        PROCEDURE_COMPONENT: procedure_score,
        TERMINOLOGY_COMPONENT: term_score,
    }
    evidence = {
        SAFETY_COMPONENT: matched_required,
        FORBIDDEN_COMPONENT: matched_forbidden,
        RULE_COMPONENT: matched_rules,
        PROCEDURE_COMPONENT: matched_procedure,
        TERMINOLOGY_COMPONENT: matched_terms,
    }
    notes = {
        SAFETY_COMPONENT: _missing_note(missing_required),
        FORBIDDEN_COMPONENT: _forbidden_note(missing_forbidden, unsafe),
        RULE_COMPONENT: _missing_note(missing_rules),
        PROCEDURE_COMPONENT: _missing_note(missing_procedure),
        TERMINOLOGY_COMPONENT: _missing_note(missing_terms),
    }
    components = [
        _component(component_id, scores[component_id], evidence[component_id], notes[component_id])
        for component_id in COMPONENT_ORDER
    ]
    gate_reasons: list[str] = []
    if required_score < 1.0:
        gate_reasons.append(
            f"required-action coverage {required_score:.6g} is below 1"
        )
    if unsafe:
        gate_reasons.append(
            "response positively recommends forbidden actions: " + "; ".join(unsafe)
        )
    diagnostics: dict[str, Any] = {
        "schema_validity": 1.0,
        "source_grounding": rule_score,
        "unsafe_recommendation_detected": float(bool(unsafe)),
        "safety_gate_applied": float(bool(gate_reasons)),
    }
    if gate_reasons:
        diagnostics["safety_gate_reasons"] = gate_reasons
    return _ledger(
        data,
        response_id,
        components,
        gate_multiplier=0.0 if gate_reasons else 1.0,
        diagnostics=diagnostics,
    )


def _ledger_for_trace(data: Railroad1959Data, trace: vf.Trace) -> dict[str, Any]:
    existing = trace.info.get("source2agent_reward_ledger")
    if isinstance(existing, dict):
        return existing
    ledger = score_response(data, _response_for_trace(trace), response_id=trace.id)
    trace.info["source2agent_reward_ledger"] = ledger
    return ledger


def _response_for_trace(trace: vf.Trace) -> str:
    symbolic_response = trace.info.get("symbolic_response")
    if isinstance(symbolic_response, str):
        return symbolic_response
    return trace.last_reply


def _parse_answer(value: str | dict[str, Any]) -> StructuredAnswer | None:
    try:
        candidate = json.loads(value) if isinstance(value, str) else value
        return StructuredAnswer.model_validate(candidate)
    except (json.JSONDecodeError, TypeError, ValidationError, ValueError):
        return None


def _component(
    component_id: str,
    score: float,
    evidence: tuple[str, ...],
    notes: str | None,
) -> dict[str, Any]:
    weight = WEIGHTS[component_id]
    return {
        "schema_version": "0.1",
        "component_id": component_id,
        "weight": weight,
        "score": score,
        "weighted_score": weight * score,
        "evidence": list(evidence),
        "notes": notes,
        "verifier_id": VERIFIER_ID,
    }


def _ledger(
    data: Railroad1959Data,
    response_id: str,
    components: list[dict[str, Any]],
    *,
    gate_multiplier: float,
    diagnostics: dict[str, Any],
) -> dict[str, Any]:
    ungated = sum(float(component["weighted_score"]) for component in components)
    if abs(ungated - 1.0) <= 1e-9:
        ungated = 1.0
    total = ungated * gate_multiplier
    if abs(total - 1.0) <= 1e-9:
        total = 1.0
    return {
        "schema_version": "0.1",
        "task_id": data.task_id,
        "response_id": response_id,
        "components": components,
        "ungated_total_score": ungated,
        "gate_multiplier": gate_multiplier,
        "total_score": total,
        "diagnostics": diagnostics,
        "verifier_id": VERIFIER_ID,
        "verifier_version": VERIFIER_VERSION,
    }


def normalize_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKC", str(value)).casefold()
    normalized = _NON_WORD_RE.sub(" ", normalized)
    return _SPACE_RE.sub(" ", normalized).strip()


def _unique(values) -> tuple[str, ...]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        key = normalize_text(value)
        if key and key not in seen:
            seen.add(key)
            result.append(str(value))
    return tuple(result)


def _coverage(expected, actual) -> tuple[float, tuple[str, ...], tuple[str, ...]]:
    expected_values = _unique(expected)
    if not expected_values:
        return 1.0, (), ()
    actual_keys = {normalize_text(value) for value in actual}
    matched = tuple(
        value for value in expected_values if normalize_text(value) in actual_keys
    )
    missing = tuple(
        value for value in expected_values if normalize_text(value) not in actual_keys
    )
    return len(matched) / len(expected_values), matched, missing


def _intersection(expected, actual) -> tuple[str, ...]:
    actual_keys = {normalize_text(value) for value in actual}
    return tuple(
        value for value in _unique(expected) if normalize_text(value) in actual_keys
    )


def _ordered_coverage(expected, actual) -> tuple[float, tuple[str, ...]]:
    expected_values = _unique(expected)
    if not expected_values:
        return 1.0, ()
    expected_keys = tuple(normalize_text(value) for value in expected_values)
    actual_keys = tuple(normalize_text(value) for value in actual)
    rows, columns = len(expected_keys) + 1, len(actual_keys) + 1
    lengths = [[0] * columns for _ in range(rows)]
    for left in range(1, rows):
        for right in range(1, columns):
            if expected_keys[left - 1] == actual_keys[right - 1]:
                lengths[left][right] = lengths[left - 1][right - 1] + 1
            else:
                lengths[left][right] = max(
                    lengths[left - 1][right], lengths[left][right - 1]
                )
    indexes: list[int] = []
    left, right = len(expected_keys), len(actual_keys)
    while left and right:
        if expected_keys[left - 1] == actual_keys[right - 1]:
            indexes.append(left - 1)
            left -= 1
            right -= 1
        elif lengths[left - 1][right] >= lengths[left][right - 1]:
            left -= 1
        else:
            right -= 1
    indexes.reverse()
    matched = tuple(expected_values[index] for index in indexes)
    return len(matched) / len(expected_values), matched


def _term_coverage(expected, final_answer: str):
    expected_values = _unique(expected)
    if not expected_values:
        return 1.0, (), ()
    padded = f" {normalize_text(final_answer)} "
    matched = tuple(
        term for term in expected_values if f" {normalize_text(term)} " in padded
    )
    missing = tuple(term for term in expected_values if term not in matched)
    return len(matched) / len(expected_values), matched, missing


def _missing(expected, matched) -> tuple[str, ...]:
    matched_keys = {normalize_text(value) for value in matched}
    return tuple(
        value for value in _unique(expected) if normalize_text(value) not in matched_keys
    )


def _missing_note(missing) -> str | None:
    return "missing: " + "; ".join(missing) if missing else None


def _forbidden_note(missing, unsafe) -> str | None:
    notes: list[str] = []
    if missing:
        notes.append("not identified as forbidden: " + "; ".join(missing))
    if unsafe:
        notes.append("positively recommended: " + "; ".join(unsafe))
    return " | ".join(notes) or None


def _sha256(value: bytes) -> str:
    return hashlib.sha256(value).hexdigest()


def _canonical_json(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
